### ISSUE TITLE
Unable to locate a class or view for component [list-button]

### ISSUE THREAD

**Issue by ferdyhape** [NirajBasnyat/crudstarter#3]
i am a newbie, when i try to create crud with example as the readme, i have a problem with this

**"Unable to locate a class or view for component [list-button]"**

thanks a lot for trying to help

**Comment by NirajBasnyat** [comment]
Hello, This error states that component list-button is not found. I couldn't reproduce this error but here is the solution:

1) Inside (resources > views) there should be components folder. check if the folder is there or not.

2) if the FOLDER IS NOT THERE you can download this package on your machine then copy (crudstarter > src > components) and paste (resources > views). Alternatively you should generate a new crud try

php artisan gen:crud Post --fields="name:str description:text" this should add components automatically

3) ) if the FOLDER IS THERE make sure the list button is also present inside components folder.

If the issue persists please feel free to contact me anytime.

**Comment by ferdyhape** [comment]
thank you @NirajBasnyat , I have done that for the experiment, but it doesn't automatically generate into the component folder, I solved it by downloading the file in the component folder in the crudstarter repository, and doing manual copying

thanks a lot @NirajBasnyat

**Comment by NirajBasnyat** [comment]
Glad it's sloved.

It should have generated the components. I tried to reproduce the error with fresh laravel install and all but to no avail. I will definitely look into it.
